### ISSUE TITLE
[FE] 사이드 바 추가 및 URL 정리

### ISSUE THREAD

**Issue by JunJI97** [modooSugangOrg/modooSugang_FE#15]
🔥 [FE] 사이드 바 추가 및 URL 정리
---
이슈 내용

로그인 화면 -> 관리자 체크박스 해제 후 로그인 시 학생 페이지, 선택 후 로그인 시 관리자 페이지
사이드바에서 항목 선택시 해당 페이지로 이동
관리자 페이지 -> 수강신청 기간 구현 

---
📋 Task

남은 기능 추가

**Comment by plooox** [comment]
#14 에서 해결!
