### ISSUE TITLE
[설계] DB 설계

### ISSUE THREAD

**Issue by plooox** [modooSugangOrg/modooSugang_FE#2]
🔥 [설계] DB 설계
---
DB 설계 부탁드립니다

📋 Task
---
- [x] 각 컴포넌트에 맞는 DB 구축
- [x] 각 DB 간 관계 정의

📚 참고자료
---
DB 구축하는 툴
- [ERD Cloud](https://www.erdcloud.com/)
- [Draw.io](https://app.diagrams.net/)

**Comment by jeongmin521** [comment]
![0401 db](https://user-images.githubusercontent.com/71782230/161205140-2955301f-7742-4880-a632-c05a1c49ae83.jpg)

**Comment by plooox** [comment]
감사합니다 👍
