### ISSUE TITLE
마이페이지 추가 및 URL 버그 수정

### ISSUE THREAD

**Issue by JunJI97** [modooSugangOrg/modooSugang_FE#25]
🔥 [FE] 마이페이지 추가 및 URL 버그 수정
---
이슈 내용

1. 로그인 -> 학생페이지 사이드바 -> 수강신청 접속 시 초기페이지로 돌아가는 문제 수정
2. 학생페이지 -> 마이페이지/신청결과 추가

![image](https://user-images.githubusercontent.com/102650903/162398722-5a6b543c-830c-4db7-bd0d-50a0dbcd1540.png)

**Comment by plooox** [comment]
확인 후  merge 했습니다
