### ISSUE TITLE
수강신청 페이지 장바구니 신청내역 테이블 추가

### ISSUE THREAD

**Issue by JunJI97** [modooSugangOrg/modooSugang_FE#41]
학생 -> 수강신청 페이지 내 두번째 자리에 장바구니 신청내역 테이블을 추가하였습니다.

수정사항 :  columns_basket, data_basket를 따로 선언하여, 기존의 columns, data와 구분해 전달했습니다.

**Comment by plooox** [comment]
확인했습니다.
감사합니다.
