### ISSUE TITLE
지워버린 Develop 브랜치 복구 & Push 오류 해결

### ISSUE THREAD

**Issue by JunJI97** [modooSugangOrg/modooSugang_FE#57]
브랜치를 지웠어도 기록이 다 남아있네요..

Push 오류 ( [remote rejected] develop -> develop (permission denied)) 해결 
->  VSCode (FE) 터미널이랑 인텔리J (BE) 터미널이랑 번갈아 쓰다보니 엉킨듯,
마지막으로 Push 성공했던 인텔리J에서 Push하니 성공

**Comment by plooox** [comment]
👍
